services:
  - type: web
    name: novaro-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: novaro-frontend
    runtime: node
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: API_PROXY_TARGET
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        sync: false
