#!/usr/bin/env bash
# Sync team photos from repo /img → frontend/public/images/team/
# Premium quality: up to 1400px edge, 94% JPEG — sharp on retina & profile modal.
# Name files by first name: kuldik.jpg, "mehul chaudhary.jpeg", etc.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/img"
DEST="$ROOT/frontend/public/images/team"
GENERATED="$ROOT/frontend/src/lib/team-photos.generated.ts"
MAX_PX=1400
JPEG_QUALITY=94

mkdir -p "$DEST"

slug_to_target() {
  case "$1" in
    kuldip) echo "kuldip-chaudhary" ;;
    mehul) echo "mehul-chaudhary" ;;
    ronak) echo "ronak-prajapati" ;;
    alpesh) echo "alpesh-prajapati" ;;
    maulik) echo "maulik-chaudhary" ;;
    krina) echo "krina-patel" ;;
    sonal) echo "sonal-chaudhary" ;;
    abhi) echo "abhi-joshi" ;;
    *) echo "" ;;
  esac
}

optimize_photo() {
  local input="$1"
  local output="$2"
  if command -v sips >/dev/null 2>&1; then
    sips -s format jpeg -s formatOptions "$JPEG_QUALITY" "$input" --out "$output" >/dev/null 2>&1
    sips -Z "$MAX_PX" "$output" >/dev/null 2>&1 || true
  else
    cp "$input" "$output"
  fi
}

synced_slugs=()

shopt -s nullglob
for file in "$SRC"/*; do
  [[ -f "$file" ]] || continue
  base=$(basename "$file")
  slug=$(echo "$base" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z].*//')
  target=$(slug_to_target "$slug")
  if [[ -z "$target" ]]; then
    echo "Skip (unknown name): $base"
    continue
  fi
  out="$DEST/${target}.jpg"
  optimize_photo "$file" "$out"
  synced_slugs+=("$slug")
  size_kb=$(du -k "$out" | cut -f1)
  echo "Synced (premium): $base → $(basename "$out") (${size_kb}KB, max ${MAX_PX}px @ ${JPEG_QUALITY}%)"
  for old in "$DEST/${target}".*; do
    [[ "$old" == "$out" ]] && continue
    rm -f "$old"
  done
done

for public_file in "$DEST"/*; do
  [[ -f "$public_file" ]] || continue
  pub_base=$(basename "$public_file")
  pub_slug=$(echo "$pub_base" | sed -E 's/-.*//')
  found=0
  for slug in "${synced_slugs[@]}"; do
    if [[ "$slug" == "$pub_slug" ]]; then
      found=1
      break
    fi
  done
  if [[ "$found" -eq 0 ]]; then
    rm -f "$public_file"
    echo "Removed stale: $pub_base"
  fi
done

{
  echo "// Auto-generated by scripts/sync-team-photos.sh — do not edit"
  echo "export const teamPhotoBySlugGenerated: Record<string, string> = {"
  for slug in "${synced_slugs[@]}"; do
    target=$(slug_to_target "$slug")
    echo "  ${slug}: \"/images/team/${target}.jpg\","
  done
  echo "};"
  echo ""
  echo "export const teamPhotosSynced = ["
  for slug in "${synced_slugs[@]}"; do
    echo "  \"${slug}\","
  done
  echo "] as const;"
} > "$GENERATED"

echo "Done. Premium photos in $DEST"
echo "Updated $GENERATED"
