// Auto-generated by scripts/sync-team-photos.sh — do not edit
export const teamPhotoBySlugGenerated: Record<string, string> = {
  abhi: "/images/team/abhi-joshi.jpg",
  alpesh: "/images/team/alpesh-prajapati.jpg",
  krina: "/images/team/krina-patel.jpg",
  kuldip: "/images/team/kuldip-chaudhary.jpg",
  maulik: "/images/team/maulik-chaudhary.jpg",
  mehul: "/images/team/mehul-chaudhary.jpg",
  sonal: "/images/team/sonal-chaudhary.jpg",
};

export const teamPhotosSynced = [
  "abhi",
  "alpesh",
  "krina",
  "kuldip",
  "maulik",
  "mehul",
  "sonal",
] as const;
